feat: Add testing to project
roamingthings/spyglass pull request #7
Opened 2023-01-22 21:46 UTC by roamingthings

This pull request adds initial tests to the project including the pull request checks.

2023-01-27 12:00 UTC, mryel00 requested changes

2023-01-27 12:00 UTC, mryel00 commented on tests/test_cli.py
> +def test_start_recording(mocker):
Exactly the same method as `test_start_server`?

2023-01-27 12:00 UTC, mryel00 commented on tests/test_cli.py
> +    # run_server(bind_address, port, output, stream_url, snapshot_url)StreamingOutput
What's up with the `StreamingOutput` at the end of the comment?

2023-01-27 12:00 UTC, mryel00 commented on tests/test_cli.py
> +def test_start_server(mocker):
Would `test_run_server` make more sense as it is testing `run_server`?

2023-01-27 12:00 UTC, mryel00 commented on .github/workflows/pull-request.yml
> +        if [ -f requirements.txt ]; then pip install -r requirements-test.txt; fi
Wouldn't it make more sense to put both in the same `if` statement if both are using the same condition?

2023-02-05 11:10 UTC, roamingthings commented
@mryel00 I've overhauled the CLI tests and workflows

2023-02-05 12:12 UTC, mryel00 approved these changes

2023-02-05 12:15 UTC, mryel00 commented
Couldn't find anything obviouslyl wrong.

2023-02-05 12:41 UTC, merged